import { TicketProps } from "./ticketprops";

export const mockData: TicketProps = {
  id: 1,
  entities_id: 2,
  name: "Não há chamados em aberto",
  date: "2023-01-01",
  closedate: null,
  solvedate: "2023-01-02",
  takeintoaccountdate: "2023-01-03",
  date_mod: "2023-01-04",
  users_id_lastupdater: 3,
  status: 4,
  users_id_recipient: 5,
  requesttypes_id: 6,
  content: "Prestamos um bom serviço",
  urgency: 7,
  impact: 8,
  priority: 9,
  itilcategories_id: 10,
  type: 11,
  global_validation: 12,
  slas_id_ttr: 13,
  slas_id_tto: 14,
  slalevels_id_ttr: 15,
  time_to_resolve: null,
  time_to_own: null,
  begin_waiting_date: "2023-01-05",
  sla_waiting_duration: 16,
  ola_waiting_duration: 17,
  olas_id_tto: 18,
  olas_id_ttr: 19,
  olalevels_id_ttr: 20,
  ola_ttr_begin_date: null,
  internal_time_to_resolve: null,
  internal_time_to_own: null,
  waiting_duration: 21,
  close_delay_stat: 22,
  solve_delay_stat: 23,
  takeintoaccount_delay_stat: 24,
  actiontime: 25,
  is_deleted: 0,
  locations_id: 26,
  validation_percent: 27,
  date_creation: "2023-01-06",
  links: [
    { rel: "self", href: "/incident/1" },
    { rel: "related", href: "/user/3" },
  ],
};
